### ISSUE TITLE
No need open/close db every time

### ISSUE THREAD

**Issue by yandrey** [antimer/lmdb#1]
It seems that this opens/closes db every request except single transaction.  We don't need open/close db every request, open only when it is not open. Not only because it is not good for performance, but also it is possible to not open if it was closed and break flock locking. Open once per process.  See LMDB docs: "Generally databases should only be opened once, by the first transaction in the process. After the first transaction completes, the database handles can freely be used by all subsequent transactions." 

Cheers

**Comment by melisgl** [comment]
This is no longer the case.
