### ISSUE TITLE
Read Transaction

### ISSUE THREAD

**Issue by ghost** [antimer/lmdb#10]
Hello!

*I am very new to common lisp, so please take this question with a grain of salt. I could be totally off base.*

It looks like this library only supports write transactions. Is that right?

From the definition of `begin-transaction` [on line 283 of lmdb.lisp](https://github.com/antimer/lmdb/blob/master/src/lmdb.lisp#L283), the flags are always being set to 0.

```lisp
(defun begin-transaction (transaction)
  "Begin the transaction.
@begin(deflist)
@term(Thread Safety)
@def(A transaction may only be used by a single thread.)
@end(deflist)"
  (with-slots (env parent) transaction
    (let ((return-code (liblmdb:txn-begin (handle env)
                                           (if parent
                                               (handle parent)
                                               (cffi:null-pointer))
                                           0  ;; <-------- txn flags
                                           (%handle transaction))))
      (alexandria:switch (return-code)
        (0
         ;; Success
         t)
        ;; TODO rest
        (t
         (unknown-error return-code))))))
```

In LMDB, only one write transaction can be processed at a time, whereas many read transactions can be processed in parallel. So, allowing read-only transactions would be nice for cases where you don't need to modify any data.

I tested out running a read-only version of the transaction, and it works by just updating the flag:

```lisp
(defun begin-read-transaction (transaction)
  "Test function to show read-only transaction."
  (with-slots (env parent) transaction
    (let ((return-code (liblmdb:txn-begin (handle env)
                                           (if parent
                                               (handle parent)
                                               (cffi:null-pointer))
                                           #x20000  ;; aka. MDB_RDONLY 
                                           (%handle transaction))))
      (alexandria:switch (return-code)
        (0
         ;; Success
         t)
        ;; TODO rest
        (t
         (unknown-error return-code))))))
```

I can see a couple possible solutions to support this workflow:

1. Provide a separate function `begin-read-transaction`
2. Provide an optional flag argument to the function, defaulting the flags to zero
3. Provide keyword arguments for each possible flag value and construct the flags based on the passed arguments

I think option 3 is probably the best bet.

Option 1 is bad b/c it's very repetitive if people want to have support for other flags too.

Option 2 is not as good as 3, because this is a high level library. So, it should do more of the heavy lifting rather than expose flags directly to the user. One way to mitigate could be a function to build the flags before passing them in.

Option 3 seems like the best, because there aren't a ton of flags people could want. And it's easy enough to build the flags based on the keyword arguments.

So the signature would be something like:

```lisp
(defun begin-transaction (transaction &key read-only)
  "Begin the transaction.
@begin(deflist)
@term(Thread Safety)
@def(A transaction may only be used by a single thread.)
@end(deflist)"
  (with-slots (env parent) transaction
    (let ((flags build-txn-flags read-only)
            (return-code (liblmdb:txn-begin (handle env)
                                           (if parent
                                               (handle parent)
                                               (cffi:null-pointer))
                                           flags
                                           (%handle transaction))))
      (alexandria:switch (return-code)
        (0
         ;; Success
         t)
        ;; TODO rest
        (t
         (unknown-error return-code))))))
```

**Comment by ghost** [comment]
It seems this version works w/ read-only transactions and maintains the write transaction as default:

```lisp
(defun build-txn-flags (read-only)
  (let ((flags 0))
    (if (not (eql read-only nil))
        (setf flags (logior flags liblmdb:+rdonly+)))
    flags))

(defun begin-transaction (transaction &key read-only)
  "Begin the transaction.

@begin(deflist)
@term(Thread Safety)

@def(A transaction may only be used by a single thread.)

@end(deflist)"
  (with-slots (env parent) transaction
    (let* ((flags (build-txn-flags read-only))
           (return-code (liblmdb:txn-begin (handle env)
                                           (if parent
                                               (handle parent)
                                               (cffi:null-pointer))
                                           flags
                                           (%handle transaction))))
      (alexandria:switch (return-code)
        (0
         ;; Success
         t)
        ;; TODO rest
        (t
         (unknown-error return-code))))))
```

**Comment by eudoxia0** [comment]
I believe the current version supports read transactions, see: https://github.com/antimer/lmdb/blob/2e60d31559a6b1d7241e64e22c8e291216f12477/src/lmdb.lisp#L1375
