### ISSUE TITLE
64-bit deployments?

### ISSUE THREAD

**Issue by lisp** [antimer/lmdb#4]
has this been used in 64-bit architectures?
there are api definitions which specify integer types when they need to specify some analog for size_t.

there is a casual note in the cffi documentation about this, but that approach does not suffice.
what is the intention for this library?

**Comment by eudoxia0** [comment]
Huh, yeah. For some reason I assumed SWIG just gave every `size_t` type the CFFI type `:pointer`. Guess this is something I should fix.

Although this worked just fine on my 64-bit machines?

**Comment by lisp** [comment]
there is at least one place where our c++ layer over lmdb uses constants which exceed 2^32.
the first observed was for the map size, but there could be others.
