### ISSUE TITLE
close-curse effects a double free

### ISSUE THREAD

**Issue by lisp** [antimer/lmdb#6]
given the respective lmdb function signatures (1,2), it looks like close-cursor should be

    (defun close-cursor (cursor)
      "Close a cursor."
      (with-slots (database) cursor
        (with-slots (transaction) database
          (liblmdb:cursor-close (handle cursor))
          (cffi:foreign-free (%handle cursor))))
      t)

the current formulation, as ` (liblmdb:cursor-close (%handle cursor))`, leads to a double-free error.

1: https://github.com/LMDB/lmdb/blob/6ac9aa666e6754f195a2e988d0c395f4d6364c28/libraries/liblmdb/mdb.c#L8384  
2: https://github.com/LMDB/lmdb/blob/6ac9aa666e6754f195a2e988d0c395f4d6364c28/libraries/liblmdb/mdb.c#L8473

**Comment by d-m-racine** [comment]
Confirmed on LMDB_0.9.22 / sbcl 1.4.6 via lmdb:do-pairs. The second evaluation of the same do-pairs form would throw a fatal double free; resolved by @lisp's suggested change.

**Comment by melisgl** [comment]
This has been fixed in the meantime.
